name: Node
trigger: change
jobs:
  SourceCodeCheck:
    image: hub.byted.org/codebase/ci_nodejs_16
    steps:
      - name: check_bnpm_repo
        commands:
          - if [ $(cat yarn.lock | grep bnpm | wc -l) -gt 0 ]; then echo "found bnpm repo url"; exit 1; fi